version: '3'

services:
  frontend:
    container_name: "chat_frontend"
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  backend:
    container_name: "chat_backend"
    volumes:
      - ./backend:/code
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_DB_HOST: chat_db
      DJANGO_DB_PORT: 5432
    env_file:
      - ./postgres.env

  db:
    container_name: "chat_db"
    image: postgres:12-alpine
    expose:
      - "5432"
    env_file:
      - ./postgres.env