version: '3'

services:
  backend:
    container_name: "chat_backend"
    volumes:
      - ./backend:/code
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DJANGO_DB_HOST: chat_db
      DJANGO_DB_PORT: 5432
    env_file:
      - ./postgres.env

  db:
    container_name: "chat_db"
    image: postgres:12-alpine
    expose:
      - "5432"
    env_file:
      - ./postgres.env