FROM python:3.8-alpine
ENV PYTHONUNBUFFERED 1
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev libffi-dev
WORKDIR /code
COPY . /code
RUN pip install -r requirements

ENTRYPOINT ["/code/entrypoint.sh"]