FROM python:3.8-alpine
ENV PYTHONUNBUFFERED 1
WORKDIR /code
COPY . /code
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
RUN pip install -r requirements

ENTRYPOINT ["/code/entrypoint.sh"]